spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://localhost:3306/u_admin_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 1
    min-idle: 3
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #是否在自动回收超时连接的时候打印连接的超时错误 
    logAbandoned: true 
    #是否自动回收超时连接 
    removeAbandoned: true
    #超时时间(以秒数为单位) 
    removeAbandonedTimeout: 180 
  redis: 
    host: localhost
    port: 6379
    password: 
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  application:
      name: user-center-api
  output: 
    ansi: 
      enabled: ALWAYS
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8888/eureka
flyway:
  enabled: true 
  url: jdbc:mysql://localhost:3306/pro_user_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
  user: root
  password: root
  check-location: true
  locations: classpath:db/migration
  validate-on-migrate: true
  clean-on-validation-error: true
  target: 1.1.0.2
  baseline-version: 0.1.0.2
  baseline-description: sdfs

server:
  port: 8001
